
server:
  port: ${EMAIL_CERT_PORT}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER}/eureka

spring:
  application:
    name: email-cert-service
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_SERVER}
    producer:
      bootstrap-servers: 10.10.10.101:9092
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PW}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  datasource:
    url: jdbc:${DB_TYPE}://${DB_ADDR}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PW}
    driver-class-name: ${DB_DRIVER}

  jpa:
    database: ${DB_TYPE}
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    show-sql: true