
jwt:
  secret-key: ${JWT}
  token:
    expired-time-ms: 1800000

server:
  port: ${GATEWAY_PORT}

# SCG
# route : predicates와 filter로 구성되어 있고 predicates에 일치하는 요청을 uri로 전달
# predicates : SCG로 들어온 요청에서 확인할 조건
# filter : SCG로 들어오는 요청에 대해 선처리 및 후처리할 때 사용하는 기능
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: member-msa
          uri: lb://MEMBER-MSA # http://localhost:8080
          predicates:
            - Path=/member/**

#        - id: monolithic-createdelete
#          uri: lb://MONOLITHIC
#          predicates:
#            - Path=/product/create
#          filters:
#            - AuthorizationHeaderFilter
#
#        - id: monolithic-find
#          uri: lb://MONOLITHIC
#          predicates:
#            - Path=/product/list, /product/{segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER}/eureka